name: 'Create Release'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Generate Release via CLI
        run: |
          currentTag=$(git describe --tags --abbrev=0)
          previousTag=$(git describe --tags --abbrev=0 $currentTag^)
          echo "currentTag: $currentTag"
          echo "previousTag: $previousTag"
          echo $(git log  --pretty=format:' * %s - %h' $previousTag..$currentTag)
          # git log  --pretty=format:' * %s - %h' $previousTag..$currentTag | gh release create ${GITHUB_REF##*/} -F -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
